[project]
name = "mlops-engineering-roadmap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Javier-DataScience", email = "alvaro.vega.vargas@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
mlops-engineering-roadmap = "mlops_engineering_roadmap:main"

[build-system]
requires = ["uv_build>=0.11.28,<0.12.0"]
build-backend = "uv_build"
